# Generated by Django 5.1.4 on 2025-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Телеграм чат-id"),
        ),
    ]
