# Generated by Django 5.1.4 on 2025-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Выберите место для привычки", max_length=255, verbose_name="Место привычки"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время для выполнения привычки", verbose_name="Время выполнения привычки"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Выберите действие привычки", max_length=255, verbose_name="Действие привычки"
                    ),
                ),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(
                        default=False, help_text="Признак на приятную привычку", verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях",
                        verbose_name="Частота привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Награду можно не указывать",
                        max_length=255,
                        null=True,
                        verbose_name="Награда за выполнение привычки",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Укажите время выполнения привычки в минутах",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Указать публичность", verbose_name="Публичность привычки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
