# Generated by Django 5.1.4 on 2025-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_related_habit_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Укажите время выполнения привычки",
                verbose_name="Время выполнение в секундах(не больше 120 с)",
            ),
        ),
    ]
